import { Composer } from "grammy";
import type { Ctx } from "../bot.js";
import { adminChatId, inlineButton, inlineKeyboard, requireOwner } from "../toolkit/index.js";
import { changeDomain, loadDomain, nextId, now } from "../domain.js";
const composer = new Composer<Ctx>();
composer.callbackQuery(/^listing:report:(.+)$/, async (ctx) => { await ctx.answerCallbackQuery(); ctx.session.step = "report-reason"; ctx.session.draft = { reportListing: ctx.match[1] }; await ctx.reply("Что не так с объявлением?", { reply_markup: inlineKeyboard([[inlineButton("Спам", "report:reason:spam")], [inlineButton("Незаконное", "report:reason:illegal")], [inlineButton("Неподобающий контент", "report:reason:inappropriate")], [inlineButton("Другое", "report:reason:other")]]) }); });
composer.callbackQuery(/^report:reason:(spam|illegal|inappropriate|other)$/, async (ctx) => { await ctx.answerCallbackQuery(); const d = ctx.session.draft ?? (ctx.session.draft = {}); d.reportReason = ctx.match[1]; ctx.session.step = "report-comment"; await ctx.reply("Добавьте короткий комментарий или напишите «нет».", { reply_markup: { force_reply: true, input_field_placeholder: "Что произошло" } }); });
composer.on("message:text", async (ctx, next) => { if (ctx.session.step !== "report-comment") return next(); const d = ctx.session.draft ?? {}; const report = { id: nextId("report"), listingId: String(d.reportListing), reporter: ctx.from?.id ?? 0, reason: String(d.reportReason), comment: ctx.message.text === "нет" ? undefined : ctx.message.text.slice(0, 500), createdAt: now() }; await changeDomain(ctx, (domain) => domain.reports.push(report)); ctx.session.step = undefined; ctx.session.draft = undefined; const admin = adminChatId(ctx); if (admin) { try { await ctx.api.sendMessage(admin, `Жалоба на объявление ${report.listingId}\nПричина: ${report.reason}${report.comment ? `\nКомментарий: ${report.comment}` : ""}`, { reply_markup: inlineKeyboard([[inlineButton("Удалить объявление", `admin:remove:${report.listingId}`), inlineButton("Заблокировать автора", `admin:ban:${report.listingId}`)]]) }); } catch { /* report remains stored */ } } await ctx.reply("Спасибо, жалоба сохранена. Мы проверим объявление."); });

async function moderate(ctx: Ctx, id: string, action: "approve" | "reject" | "remove" | "ban") { if (!(await requireOwner(ctx))) return; const user = ctx.from?.id ?? 0; let owner: number | undefined; let found = false; await changeDomain(ctx, (d) => { const x = d.listings.find((v) => v.id === id); if (!x) return; found = true; owner = x.owner; if (action === "approve") x.status = "published"; if (action === "reject" || action === "remove" || action === "ban") x.status = "removed"; if (action === "ban" && !d.banned.includes(x.owner)) d.banned.push(x.owner); if (action === "ban") for (const listing of d.listings) if (listing.owner === x.owner && listing.status !== "sold") listing.status = "removed"; d.history.push({ listingId: id, action: action === "approve" ? "approved" : action === "reject" ? "rejected" : action === "remove" ? "removed" : "banned", by: user, at: now() }); }); if (!found) { await ctx.editMessageText("Объявление уже удалено или не найдено."); return; } if (owner !== undefined && action !== "ban") { try { await ctx.api.sendMessage(owner, action === "approve" ? "Ваше объявление прошло проверку и опубликовано." : "Ваше объявление снято с публикации."); } catch { /* a blocked user must not break moderation */ } } await ctx.editMessageText(action === "approve" ? "Объявление опубликовано." : action === "ban" ? "Автор заблокирован, его объявления сняты." : "Объявление снято с публикации."); }
composer.callbackQuery(/^admin:(approve|reject|remove|ban):(.+)$/, async (ctx) => { await ctx.answerCallbackQuery(); await moderate(ctx, ctx.match[2], ctx.match[1] as "approve" | "reject" | "remove" | "ban"); });
export default composer;
